name: Publish

on:
  release:
    types: [published]

jobs:
  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: faberNovel/xcresource-cli
          tap: faberNovel/homebrew-formulae
          formula: Formula/xcresource.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_CI }}
